version: "3"

services: 
    frontend:
        container_name: frontend
        restart: always
        image: edaral3/frontend:latest
        command: npm start
        ports:
            - "80:3000"

    backend:
        container_name: backend
        restart: always
        image: edaral3/backend:latest
        command: node index.js
        ports:
            - "4002:4002"
